import { createServerFn } from "@tanstack/react-start";
import {
  CATEGORY_FOLDERS,
  MAX_BYTES,
  REPO_LIMIT,
  isVideoExt,
  safeExt,
  slugify,
  uploadInputSchema,
  type SaveResult,
} from "./media-categories";

export const saveMediaBatch = createServerFn({ method: "POST" })
  .inputValidator((data: unknown) => uploadInputSchema.parse(data))
  .handler(async ({ data }): Promise<SaveResult> => {
    if (process.env["NODE_ENV"] !== "development") {
      throw new Error(
        "Media uploads only work inside the Lovable editor preview, where project files are writable.",
      );
    }

    const fs = await import("node:fs/promises");
    const path = await import("node:path");
    const crypto = await import("node:crypto");
    const { execFile } = await import("node:child_process");

    const root = process.cwd();
    const assetsRoot = path.join(root, "src", "assets");
    const manifestPath = path.join(root, "src", "data", "uploaded-media.manifest.json");

    type ManifestEntry = {
      id: string;
      title: string;
      category: string;
      file: string;
      kind: "image" | "video";
      hash: string;
    };

    let manifest: ManifestEntry[] = [];
    try {
      manifest = JSON.parse(await fs.readFile(manifestPath, "utf8")) as ManifestEntry[];
    } catch {
      manifest = [];
    }

    // Hash everything already in src/assets so the same photo never appears twice.
    const existingHashes = new Set<string>();
    const walk = async (dir: string): Promise<void> => {
      let entries: { name: string; isDirectory: () => boolean }[] = [];
      try {
        entries = (await fs.readdir(dir, { withFileTypes: true })) as unknown as {
          name: string;
          isDirectory: () => boolean;
        }[];
      } catch {
        return;
      }
      for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          await walk(full);
        } else if (safeExt(entry.name)) {
          const buf = await fs.readFile(full);
          existingHashes.add(crypto.createHash("sha256").update(buf).digest("hex"));
        }
      }
    };
    await walk(assetsRoot);

    const renderModule = (entries: ManifestEntry[]) => {
      const imports = entries
        .map((entry, index) => `import m${index} from "@/assets/${entry.file}";`)
        .join("\n");
      const line = (entry: ManifestEntry, index: number) =>
        `  { id: ${JSON.stringify(entry.id)}, title: ${JSON.stringify(entry.title)}, category: ${JSON.stringify(
          entry.category,
        )}, ${entry.kind === "video" ? "src" : "image"}: m${index} },`;
      const pick = (kind: "image" | "video") =>
        entries
          .map((entry, index) => (entry.kind === kind ? line(entry, index) : null))
          .filter(Boolean)
          .join("\n");

      return `// AUTO-GENERATED by the /upload page (editor preview only).
// Do not reorder entries: Reference IDs are assigned from this order and must stay stable.
${imports ? `${imports}\n` : ""}
export type UploadedItem = {
  id: string;
  title: string;
  category: string;
  image?: string;
  src?: string;
};

export const uploadedProjects: UploadedItem[] = [
${pick("image")}
];

export const uploadedVideos: UploadedItem[] = [
${pick("video")}
];
`;
    };

    const result: SaveResult = { saved: [], skipped: [] };

    for (const file of data.files) {
      const ext = safeExt(file.name);
      if (!ext) {
        result.skipped.push({ name: file.name, reason: "Unsupported file type" });
        continue;
      }

      const buffer = Buffer.from(file.content, "base64");
      if (buffer.byteLength === 0 || buffer.byteLength > MAX_BYTES) {
        result.skipped.push({ name: file.name, reason: "File is empty or larger than 60 MB" });
        continue;
      }

      const hash = crypto.createHash("sha256").update(buffer).digest("hex");
      if (existingHashes.has(hash)) {
        result.skipped.push({ name: file.name, reason: "Already in the gallery" });
        continue;
      }

      const kind: "image" | "video" = isVideoExt(ext) ? "video" : "image";
      const folder = CATEGORY_FOLDERS[file.category]!;
      const dir = path.join(assetsRoot, folder);
      await fs.mkdir(dir, { recursive: true });

      const base = slugify(file.title) || slugify(file.name.replace(/\.[^.]+$/, "")) || "item";
      let fileName = `${base}.${ext}`;
      let counter = 2;
      while (
        await fs
          .stat(path.join(dir, fileName))
          .then(() => true)
          .catch(() => false)
      ) {
        fileName = `${base}-${counter++}.${ext}`;
      }
      let target = path.join(dir, fileName);
      await fs.writeFile(target, buffer);

      // Keep every committed file under the 10 MB repository limit.
      if (kind === "video" && buffer.byteLength > REPO_LIMIT) {
        const compressed = target.replace(/\.[^.]+$/, "-compressed.mp4");
        const ok = await new Promise<boolean>((resolve) => {
          execFile(
            "ffmpeg",
            [
              "-y", "-i", target,
              "-c:v", "libx264", "-crf", "30", "-preset", "veryfast",
              "-vf", "scale='min(1280,iw)':-2",
              "-c:a", "aac", "-b:a", "96k",
              compressed,
            ],
            (error) => resolve(!error),
          );
        });

        const smallEnough =
          ok &&
          (await fs
            .stat(compressed)
            .then((s) => s.size > 0 && s.size < REPO_LIMIT)
            .catch(() => false));

        if (smallEnough) {
          await fs.rm(target);
          target = compressed;
          fileName = path.basename(compressed);
        } else {
          await fs.rm(target).catch(() => undefined);
          await fs.rm(compressed).catch(() => undefined);
          result.skipped.push({
            name: file.name,
            reason: "Video is over 10 MB and could not be compressed automatically",
          });
          continue;
        }
      }

      existingHashes.add(hash);
      let id = `up-${base}`;
      while (manifest.some((m) => m.id === id)) id = `${id}-x`;
      manifest.push({
        id,
        title: file.title,
        category: file.category,
        file: `${folder}/${fileName}`,
        kind,
        hash,
      });
      result.saved.push({
        refName: `${folder}/${fileName}`,
        title: file.title,
        category: file.category,
        kind,
      });
    }

    if (result.saved.length > 0) {
      await fs.writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
      await fs.writeFile(
        path.join(root, "src", "data", "uploaded-media.ts"),
        renderModule(manifest),
        "utf8",
      );
    }

    return result;
  });
