// AUTO-GENERATED by the /upload page (editor preview only).
// Do not reorder entries: Reference IDs are assigned from this order and must stay stable.
import m0 from "@/assets/kitchen/test-1.jpg";
import m1 from "@/assets/kitchen/test-2.jpg";

export type UploadedItem = {
  id: string;
  title: string;
  category: string;
  image?: string;
  src?: string;
};

export const uploadedProjects: UploadedItem[] = [
  { id: "up-test-1", title: "Test 1", category: "Kitchen Cabinets", image: m0 },
  { id: "up-test-2", title: "Test 2", category: "Kitchen Cabinets", image: m1 },
];

export const uploadedVideos: UploadedItem[] = [

];
