// AUTO-GENERATED by the /upload page (editor preview only).
// Entries are appended here so the hand-maintained arrays in projects.ts and
// videos.ts keep their order and every Reference ID stays stable.
// Safe to edit by hand: titles and categories only — never reorder entries.

export type UploadedItem = {
  id: string;
  title: string;
  category: string;
  image?: string;
  src?: string;
};

export const uploadedProjects: UploadedItem[] = [];

export const uploadedVideos: UploadedItem[] = [];
