// AUTO-GENERATED by the /upload page (editor preview only).
// Do not reorder entries: Reference IDs are assigned from this order and must stay stable.

export type UploadedItem = {
  id: string;
  title: string;
  category: string;
  image?: string;
  src?: string;
};

export const uploadedProjects: UploadedItem[] = [];

export const uploadedVideos: UploadedItem[] = [];
